export const dataDummyEmployee = [
    {
      id:'1',
      user_name: "jdoe1",
      first_name: "John",
      last_name: "1",
      email: "john.doe1@example.com",
      birth_date: "1611979250",
      basic_salary: 50000,
      status: "active",
      group: "A",
      description: "John is a software developer."
    },
    {
      id: '2',
      user_name: "jdoe2",
      first_name: "John",
      last_name: "2",
      email: "jane.jdoe2@example.com",
      birth_date: "1611979250",
      basic_salary: 60000,
      status: "inactive",
      group: "B",
      description: "Jane is a project manager."
    },
    {
      id:'3',
      user_name: "wbrown3",
      first_name: "Will",
      last_name: "3",
      email: "will.brown3@example.com",
      birth_date: "1611979250",
      basic_salary: 55000,
      status: "inactive",
      group: "A",
      description: "Will is a graphic designer."
    },
    {
      id:'4',
      user_name: "ljones4",
      first_name: "Lisa",
      last_name: "4",
      email: "lisa.jones4@example.com",
      birth_date: "1611979250",
      basic_salary: 70000,
      status: "active",
      group: "C",
      description: "Lisa is a data analyst."
    },
    {
      id:'5',
      user_name: "pwhite5",
      first_name: "Paul",
      last_name: "5",
      email: "paul.white5@example.com",
      birth_date: "1611979250",
      basic_salary: 48000,
      status: "active",
      group: "B",
      description: "Paul is a marketing specialist."
    },
    {
      id:'6',
      user_name: "kgreen6",
      first_name: "Kate",
      last_name: "6",
      email: "kate.green6@example.com",
      birth_date: "1611979250",
      basic_salary: 63000,
      status: "inactive",
      group: "C",
      description: "Kate is a financial analyst."
    },
    {
      id:'7',
      user_name: "mthompson7",
      first_name: "Mike",
      last_name: "7",
      email: "mike.thompson7@example.com",
      birth_date: "1611979250",
      basic_salary: 59000,
      status: "active",
      group: "A",
      description: "Mike is a sales manager."
    },
    {
      id:'8',
      user_name: "sroberts8",
      first_name: "Sarah",
      last_name: "8",
      email: "sarah.roberts8@example.com",
      birth_date: "1611979250",
      basic_salary: 62000,
      status: "active",
      group: "B",
      description: "Sarah is a HR specialist."
    },
    {
      id:'9',
      user_name: "bdavis9",
      first_name: "Brian",
      last_name: "9",
      email: "brian.davis9@example.com",
      birth_date: "1611979250",
      basic_salary: 54000,
      status: "inactive",
      group: "C",
      description: "Brian is a content writer."
    },
    {
      id:'10',
      user_name: "amartin10",
      first_name: "Amy",
      last_name: "10",
      email: "amy.martin10@example.com",
      birth_date: "1611979250",
      basic_salary: 61000,
      status: "active",
      group: "A",
      description: "Amy is a product manager."
    },
    {
      id:'11',
      user_name: "rking11",
      first_name: "Robert",
      last_name: "11",
      email: "robert.king11@example.com",
      birth_date: "1611979250",
      basic_salary: 67000,
      status: "active",
      group: "B",
      description: "Robert is a UX designer."
    },
    {
      id:'12',
      user_name: "jlee12",
      first_name: "Jessica",
      last_name: "12",
      email: "jessica.lee12@example.com",
      birth_date: "1611979250",
      basic_salary: 58000,
      status: "inactive",
      group: "C",
      description: "Jessica is a QA engineer."
    },
    {
      id:'13',
      user_name: "wdiaz13",
      first_name: "William",
      last_name: "13",
      email: "william.diaz13@example.com",
      birth_date: "1611979250",
      basic_salary: 56000,
      status: "active",
      group: "A",
      description: "William is a system administrator."
    },
    {
      id:'14',
      user_name: "slopez14",
      first_name: "Sophie",
      last_name: "14",
      email: "sophie.lopez14@example.com",
      birth_date: "1611979250",
      basic_salary: 69000,
      status: "active",
      group: "B",
      description: "Sophie is a business analyst."
    },
    {
      id:'15',
      user_name: "dmoore15",
      first_name: "David",
      last_name: "15",
      email: "david.moore15@example.com",
      birth_date: "1611979250",
      basic_salary: 65000,
      status: "inactive",
      group: "C",
      description: "David is a network engineer."
    },
    {
      id:'16',
      user_name: "mgonzalez16",
      first_name: "Maria",
      last_name: "16",
      email: "maria.gonzalez16@example.com",
      birth_date: "1611979250",
      basic_salary: 64000,
      status: "active",
      group: "A",
      description: "Maria is a support specialist."
    },
    {
      id:'17',
      user_name: "jmartinez17",
      first_name: "James",
      last_name: "17",
      email: "james.martinez17@example.com",
      birth_date: "1611979250",
      basic_salary: 57000,
      status: "active",
      group: "B",
      description: "James is a web developer."
    },
    {
      id:'18',
      user_name: "achavez18",
      first_name: "Anna",
      last_name: "18",
      email: "anna.chavez18@example.com",
      birth_date: "1611979250",
      basic_salary: 53000,
      status: "inactive",
      group: "C",
      description: "Anna is a technical writer."
    },
    {
      id:'19',
      user_name: "tgarcia19",
      first_name: "Tom",
      last_name: "19",
      email: "tom.garcia19@example.com",
      birth_date: "1611979250",
      basic_salary: 59000,
      status: "active",
      group: "A",
      description: "Tom is a cloud engineer."
    },
    {
      id:'20',
      user_name: "mhernandez20",
      first_name: "Megan",
      last_name: "20",
      email: "megan.hernandez20@example.com",
      birth_date: "1611979250",
      basic_salary: 60000,
      status: "active",
      group: "B",
      description: "Megan is a SEO specialist."
    },
    {
      id: '21',
      user_name: "ylopez21",
      first_name: "Yvonne",
      last_name: "21",
      email: "yvonne.lopez21@example.com",
      birth_date: "1611979250",
      basic_salary: 61000,
      status: "inactive",
      group: "C",
      description: "Yvonne is a software architect."
    },
    {
      id: '22',
      user_name: "rhill22",
      first_name: "Rachel",
      last_name: "22",
      email: "rachel.hill22@example.com",
      birth_date: "1611979250",
      basic_salary: 57000,
      status: "active",
      group: "A",
      description: "Rachel is a data engineer."
    },
    {
      id: '23',
      user_name: "adavis23",
      first_name: "Aaron",
      last_name: "23",
      email: "aaron.davis23@example.com",
      birth_date: "1611979250",
      basic_salary: 62000,
      status: "active",
      group: "B",
      description: "Aaron is a front-end developer."
    },
    {
      id: '24',
      user_name: "kdavis24",
      first_name: "Kevin",
      last_name: "24",
      email: "kevin.davis24@example.com",
      birth_date: "1611979250",
      basic_salary: 65000,
      status: "inactive",
      group: "C",
      description: "Kevin is a back-end developer."
    },
    {
      id: '25',
      user_name: "tturner25",
      first_name: "Tina",
      last_name: "25",
      email: "tina.turner25@example.com",
      birth_date: "1611979250",
      basic_salary: 68000,
      status: "active",
      group: "A",
      description: "Tina is a UI/UX designer."
    },
    {
        id: '26',
        user_name: "jdoe26",
        first_name: "John",
        last_name: "26",
        email: "john.doe1@example.com",
        birth_date: "1611979250",
        basic_salary: 50000,
        status: "active",
        group: "A",
        description: "John is a software developer."
      },
      {
        id: '27',
        user_name: "jsmith27",
        first_name: "Jane",
        last_name: "27",
        email: "jane.smith2@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Jane is a project manager."
      },
      {
        id: '28',
        user_name: "wbrown28",
        first_name: "Will",
        last_name: "28",
        email: "will.brown3@example.com",
        birth_date: "1611979250",
        basic_salary: 55000,
        status: "inactive",
        group: "A",
        description: "Will is a graphic designer."
      },
      {
        id: '29',
        user_name: "ljones29",
        first_name: "Lisa",
        last_name: "29",
        email: "lisa.jones4@example.com",
        birth_date: "1611979250",
        basic_salary: 70000,
        status: "active",
        group: "C",
        description: "Lisa is a data analyst."
      },
      {
        id: '30',
        user_name: "pwhite30",
        first_name: "Paul",
        last_name: "30",
        email: "paul.white5@example.com",
        birth_date: "1611979250",
        basic_salary: 48000,
        status: "active",
        group: "B",
        description: "Paul is a marketing specialist."
      },
      {
        id:'31',
        user_name: "kgreen31",
        first_name: "Kate",
        last_name: "31",
        email: "kate.green6@example.com",
        birth_date: "1611979250",
        basic_salary: 63000,
        status: "inactive",
        group: "C",
        description: "Kate is a financial analyst."
      },
      {
        id:'32',
        user_name: "mthompson32",
        first_name: "Mike",
        last_name: "32",
        email: "mike.thompson7@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Mike is a sales manager."
      },
      {
        id:'33',
        user_name: "sroberts33",
        first_name: "Sarah",
        last_name: "33",
        email: "sarah.roberts8@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Sarah is a HR specialist."
      },
      {
        id:'34',
        user_name: "bdavis34",
        first_name: "Brian",
        last_name: "34",
        email: "brian.davis9@example.com",
        birth_date: "1611979250",
        basic_salary: 54000,
        status: "inactive",
        group: "C",
        description: "Brian is a content writer."
      },
      {
        id:'36',
        user_name: "amartin35",
        first_name: "Amy",
        last_name: "35",
        email: "amy.martin10@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "active",
        group: "A",
        description: "Amy is a product manager."
      },
      {
        id:'36',
        user_name: "rking36",
        first_name: "Robert",
        last_name: "36",
        email: "robert.king11@example.com",
        birth_date: "1611979250",
        basic_salary: 67000,
        status: "active",
        group: "B",
        description: "Robert is a UX designer."
      },
      {
        id:'37',
        user_name: "jlee137",
        first_name: "Jessica",
        last_name: "37",
        email: "jessica.lee12@example.com",
        birth_date: "1611979250",
        basic_salary: 58000,
        status: "inactive",
        group: "C",
        description: "Jessica is a QA engineer."
      },
      {
        id:'38',
        user_name: "wdiaz38",
        first_name: "William",
        last_name: "38",
        email: "william.diaz13@example.com",
        birth_date: "1611979250",
        basic_salary: 56000,
        status: "active",
        group: "A",
        description: "William is a system administrator."
      },
      {
        id:'39',
        user_name: "slopez39",
        first_name: "Sophie",
        last_name: "39",
        email: "sophie.lopez14@example.com",
        birth_date: "1611979250",
        basic_salary: 69000,
        status: "active",
        group: "B",
        description: "Sophie is a business analyst."
      },
      {
        id:'40',
        user_name: "dmoore40",
        first_name: "David",
        last_name: "40",
        email: "david.moore15@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "David is a network engineer."
      },
      {
        id:'41',
        user_name: "mgonzalez41",
        first_name: "Maria",
        last_name: "41",
        email: "maria.gonzalez16@example.com",
        birth_date: "1611979250",
        basic_salary: 64000,
        status: "active",
        group: "A",
        description: "Maria is a support specialist."
      },
      {
        id:'42',
        user_name: "jmartinez42",
        first_name: "James",
        last_name: "42",
        email: "james.martinez17@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "B",
        description: "James is a web developer."
      },
      {
        id:'43',
        user_name: "achavez43",
        first_name: "Anna",
        last_name: "43",
        email: "anna.chavez18@example.com",
        birth_date: "1611979250",
        basic_salary: 53000,
        status: "inactive",
        group: "C",
        description: "Anna is a technical writer."
      },
      {
        id:'44',
        user_name: "tgarcia44",
        first_name: "Tom",
        last_name: "44",
        email: "tom.garcia19@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Tom is a cloud engineer."
      },
      {
        id:'45',
        user_name: "mhernandez45",
        first_name: "Megan",
        last_name: "45",
        email: "megan.hernandez20@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Megan is a SEO specialist."
      },
      {
        id:'46',
        user_name: "ylopez46",
        first_name: "Yvonne",
        last_name: "46",
        email: "yvonne.lopez21@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "inactive",
        group: "C",
        description: "Yvonne is a software architect."
      },
      {
        id:'47',
        user_name: "rhill47",
        first_name: "Rachel",
        last_name: "47",
        email: "rachel.hill22@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "A",
        description: "Rachel is a data engineer."
      },
      {
        id:'48',
        user_name: "adavis48",
        first_name: "Aaron",
        last_name: "48",
        email: "aaron.davis23@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Aaron is a front-end developer."
      },
      {
        id:'49',
        user_name: "kdavis49",
        first_name: "Kevin",
        last_name: "49",
        email: "kevin.davis24@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "Kevin is a back-end developer."
      },
      {
        id:'50',
        user_name: "tturner50",
        first_name: "Tina",
        last_name: "50",
        email: "tina.turner25@example.com",
        birth_date: "1611979250",
        basic_salary: 68000,
        status: "active",
        group: "A",
        description: "Tina is a UI/UX designer."
      },
      {
        id:'51',
        user_name: "jdoe51",
        first_name: "John",
        last_name: "51",
        email: "john.doe1@example.com",
        birth_date: "1611979250",
        basic_salary: 50000,
        status: "active",
        group: "A",
        description: "John is a software developer."
      },
      {
        id:'52',
        user_name: "jsmith52",
        first_name: "Jane",
        last_name: "52",
        email: "jane.smith2@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Jane is a project manager."
      },
      {
        id:'53',
        user_name: "wbrown53",
        first_name: "Will",
        last_name: "53",
        email: "will.brown3@example.com",
        birth_date: "1611979250",
        basic_salary: 55000,
        status: "inactive",
        group: "A",
        description: "Will is a graphic designer."
      },
      {
        id:'54',
        user_name: "ljones54",
        first_name: "Lisa",
        last_name: "54",
        email: "lisa.jones4@example.com",
        birth_date: "1611979250",
        basic_salary: 70000,
        status: "active",
        group: "C",
        description: "Lisa is a data analyst."
      },
      {
        id:'55',
        user_name: "pwhite55",
        first_name: "Paul",
        last_name: "55",
        email: "paul.white5@example.com",
        birth_date: "1611979250",
        basic_salary: 48000,
        status: "active",
        group: "B",
        description: "Paul is a marketing specialist."
      },
      {
        id:'56',
        user_name: "kgreen56",
        first_name: "Kate",
        last_name: "56",
        email: "kate.green6@example.com",
        birth_date: "1611979250",
        basic_salary: 63000,
        status: "inactive",
        group: "C",
        description: "Kate is a financial analyst."
      },
      {
        id:'57',
        user_name: "mthompson57",
        first_name: "Mike",
        last_name: "57",
        email: "mike.thompson7@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Mike is a sales manager."
      },
      {
        id:'58',
        user_name: "sroberts58",
        first_name: "Sarah",
        last_name: "58",
        email: "sarah.roberts8@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Sarah is a HR specialist."
      },
      {
        id:'59',
        user_name: "bdavis59",
        first_name: "Brian",
        last_name: "59",
        email: "brian.davis9@example.com",
        birth_date: "1611979250",
        basic_salary: 54000,
        status: "inactive",
        group: "C",
        description: "Brian is a content writer."
      },
      {
        id:'60',
        user_name: "amartin60",
        first_name: "Amy",
        last_name: "60",
        email: "amy.martin10@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "active",
        group: "A",
        description: "Amy is a product manager."
      },
      {
        id:'61',
        user_name: "rking61",
        first_name: "Robert",
        last_name: "61",
        email: "robert.king11@example.com",
        birth_date: "1611979250",
        basic_salary: 67000,
        status: "active",
        group: "B",
        description: "Robert is a UX designer."
      },
      {
        id:'62',
        user_name: "jlee162",
        first_name: "Jessica",
        last_name: "62",
        email: "jessica.lee12@example.com",
        birth_date: "1611979250",
        basic_salary: 58000,
        status: "inactive",
        group: "C",
        description: "Jessica is a QA engineer."
      },
      {
        id:'63',
        user_name: "wdiaz63",
        first_name: "William",
        last_name: "63",
        email: "william.diaz13@example.com",
        birth_date: "1611979250",
        basic_salary: 56000,
        status: "active",
        group: "A",
        description: "William is a system administrator."
      },
      {
        id:'64',
        user_name: "slopez64",
        first_name: "Sophie",
        last_name: "64",
        email: "sophie.lopez14@example.com",
        birth_date: "1611979250",
        basic_salary: 69000,
        status: "active",
        group: "B",
        description: "Sophie is a business analyst."
      },
      {
        id:'65',
        user_name: "dmoore65",
        first_name: "David",
        last_name: "65",
        email: "david.moore15@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "David is a network engineer."
      },
      {
        id:'66',
        user_name: "mgonzalez66",
        first_name: "Maria",
        last_name: "66",
        email: "maria.gonzalez16@example.com",
        birth_date: "1611979250",
        basic_salary: 64000,
        status: "active",
        group: "A",
        description: "Maria is a support specialist."
      },
      {
        id:'67',
        user_name: "jmartinez67",
        first_name: "James",
        last_name: "67",
        email: "james.martinez17@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "B",
        description: "James is a web developer."
      },
      {
        id:'68',
        user_name: "achavez68",
        first_name: "Anna",
        last_name: "68",
        email: "anna.chavez18@example.com",
        birth_date: "1611979250",
        basic_salary: 53000,
        status: "inactive",
        group: "C",
        description: "Anna is a technical writer."
      },
      {
        id:'69',
        user_name: "tgarcia69",
        first_name: "Tom",
        last_name: "69",
        email: "tom.garcia19@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Tom is a cloud engineer."
      },
      {
        id:'70',
        user_name: "mhernandez70",
        first_name: "Megan",
        last_name: "70",
        email: "megan.hernandez20@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Megan is a SEO specialist."
      },
      {
        id:'71',
        user_name: "ylopez71",
        first_name: "Yvonne",
        last_name: "71",
        email: "yvonne.lopez21@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "inactive",
        group: "C",
        description: "Yvonne is a software architect."
      },
      {
        id:'72',
        user_name: "rhill72",
        first_name: "Rachel",
        last_name: "72",
        email: "rachel.hill22@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "A",
        description: "Rachel is a data engineer."
      },
      {
        id:'73',
        user_name: "adavis73",
        first_name: "Aaron",
        last_name: "73",
        email: "aaron.davis23@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Aaron is a front-end developer."
      },
      {
        id:'74',
        user_name: "kdavis74",
        first_name: "Kevin",
        last_name: "74",
        email: "kevin.davis24@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "Kevin is a back-end developer."
      },
      {
        id:'75',
        user_name: "tturner75",
        first_name: "Tina",
        last_name: "75",
        email: "tina.turner25@example.com",
        birth_date: "1611979250",
        basic_salary: 68000,
        status: "active",
        group: "A",
        description: "Tina is a UI/UX designer."
      },
      {
        id:'76',
        user_name: "jdoe76",
        first_name: "John",
        last_name: "76",
        email: "john.doe1@example.com",
        birth_date: "1611979250",
        basic_salary: 50000,
        status: "active",
        group: "A",
        description: "John is a software developer."
      },
      {
        id:'77',
        user_name: "jsmith77",
        first_name: "Jane",
        last_name: "77",
        email: "jane.smith2@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Jane is a project manager."
      },
      {
        id:'78',
        user_name: "wbrown78",
        first_name: "Will",
        last_name: "78",
        email: "will.brown3@example.com",
        birth_date: "1611979250",
        basic_salary: 55000,
        status: "inactive",
        group: "A",
        description: "Will is a graphic designer."
      },
      {
        id:'79',
        user_name: "ljones79",
        first_name: "Lisa",
        last_name: "79",
        email: "lisa.jones4@example.com",
        birth_date: "1611979250",
        basic_salary: 70000,
        status: "active",
        group: "C",
        description: "Lisa is a data analyst."
      },
      {
        id:'80',
        user_name: "pwhite80",
        first_name: "Paul",
        last_name: "80",
        email: "paul.white5@example.com",
        birth_date: "1611979250",
        basic_salary: 48000,
        status: "active",
        group: "B",
        description: "Paul is a marketing specialist."
      },
      {
        id:'81',
        user_name: "kgreen81",
        first_name: "Kate",
        last_name: "81",
        email: "kate.green6@example.com",
        birth_date: "1611979250",
        basic_salary: 63000,
        status: "inactive",
        group: "C",
        description: "Kate is a financial analyst."
      },
      {
        id:'82',
        user_name: "mthompson82",
        first_name: "Mike",
        last_name: "82",
        email: "mike.thompson7@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Mike is a sales manager."
      },
      {
        id:'83',
        user_name: "sroberts83",
        first_name: "Sarah",
        last_name: "83",
        email: "sarah.roberts8@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Sarah is a HR specialist."
      },
      {
        id:'84',
        user_name: "bdavis84",
        first_name: "Brian",
        last_name: "84",
        email: "brian.davis9@example.com",
        birth_date: "1611979250",
        basic_salary: 54000,
        status: "inactive",
        group: "C",
        description: "Brian is a content writer."
      },
      {
        id:'85',
        user_name: "amartin85",
        first_name: "Amy",
        last_name: "85",
        email: "amy.martin10@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "active",
        group: "A",
        description: "Amy is a product manager."
      },
      {
        id:'86',
        user_name: "rking86",
        first_name: "Robert",
        last_name: "86",
        email: "robert.king11@example.com",
        birth_date: "1611979250",
        basic_salary: 67000,
        status: "active",
        group: "B",
        description: "Robert is a UX designer."
      },
      {
        id:'87',
        user_name: "jlee187",
        first_name: "Jessica",
        last_name: "87",
        email: "jessica.lee12@example.com",
        birth_date: "1611979250",
        basic_salary: 58000,
        status: "inactive",
        group: "C",
        description: "Jessica is a QA engineer."
      },
      {
        id:'88',
        user_name: "wdiaz88",
        first_name: "William",
        last_name: "88",
        email: "william.diaz13@example.com",
        birth_date: "1611979250",
        basic_salary: 56000,
        status: "active",
        group: "A",
        description: "William is a system administrator."
      },
      {
        id:'89',
        user_name: "slopez89",
        first_name: "Sophie",
        last_name: "89",
        email: "sophie.lopez14@example.com",
        birth_date: "1611979250",
        basic_salary: 69000,
        status: "active",
        group: "B",
        description: "Sophie is a business analyst."
      },
      {
        id:'90',
        user_name: "dmoore90",
        first_name: "David",
        last_name: "90",
        email: "david.moore15@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "David is a network engineer."
      },
      {
        id:'91',
        user_name: "mgonzale91",
        first_name: "Maria",
        last_name: "91",
        email: "maria.gonzalez16@example.com",
        birth_date: "1611979250",
        basic_salary: 64000,
        status: "active",
        group: "A",
        description: "Maria is a support specialist."
      },
      {
        id:'92',
        user_name: "jmartinez92",
        first_name: "James",
        last_name: "92",
        email: "james.martinez17@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "B",
        description: "James is a web developer."
      },
      {
        id:'93',
        user_name: "achavez93",
        first_name: "Anna",
        last_name: "93",
        email: "anna.chavez18@example.com",
        birth_date: "1611979250",
        basic_salary: 53000,
        status: "inactive",
        group: "C",
        description: "Anna is a technical writer."
      },
      {
        id:'94',
        user_name: "tgarcia94",
        first_name: "Tom",
        last_name: "94",
        email: "tom.garcia19@example.com",
        birth_date: "1611979250",
        basic_salary: 59000,
        status: "active",
        group: "A",
        description: "Tom is a cloud engineer."
      },
      {
        id:'95',
        user_name: "mhernandez95",
        first_name: "Megan",
        last_name: "95",
        email: "megan.hernandez20@example.com",
        birth_date: "1611979250",
        basic_salary: 60000,
        status: "active",
        group: "B",
        description: "Megan is a SEO specialist."
      },
      {
        id:'96',
        user_name: "ylopez96",
        first_name: "Yvonne",
        last_name: "96",
        email: "yvonne.lopez21@example.com",
        birth_date: "1611979250",
        basic_salary: 61000,
        status: "inactive",
        group: "C",
        description: "Yvonne is a software architect."
      },
      {
        id:'97',
        user_name: "rhill97",
        first_name: "Rachel",
        last_name: "97",
        email: "rachel.hill22@example.com",
        birth_date: "1611979250",
        basic_salary: 57000,
        status: "active",
        group: "A",
        description: "Rachel is a data engineer."
      },
      {
        id:'98',
        user_name: "adavis98",
        first_name: "Aaron",
        last_name: "98",
        email: "aaron.davis23@example.com",
        birth_date: "1611979250",
        basic_salary: 62000,
        status: "active",
        group: "B",
        description: "Aaron is a front-end developer."
      },
      {
        id:'99',
        user_name: "kdavis99",
        first_name: "Kevin",
        last_name: "99",
        email: "kevin.davis24@example.com",
        birth_date: "1611979250",
        basic_salary: 65000,
        status: "inactive",
        group: "C",
        description: "Kevin is a back-end developer."
      },
      {
        id:'100',
        user_name: "tturner100",
        first_name: "Tina",
        last_name: "100",
        email: "tina.turner25@example.com",
        birth_date: "1611979250",
        basic_salary: 68000,
        status: "active",
        group: "A",
        description: "Tina is a UI/UX designer."
      }
  ];